version = 0.1
[default.deploy.parameters]
stack_name = "connect-halopsa-integration"
resolve_s3 = true
s3_prefix = "connect-halopsa-integration"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "StackName=\"connect-halopsa-integration\" Environment=\"production\""
disable_rollback = true
